env:
  - COMMUNITY_DISTRIBUTION_URL=https://download.alfresco.com/release/community/201707-build-00028/alfresco-community-distribution-201707.zip ALFRESCO_COMMUNITY_VALIDATOR_TESTS=https://github.com/paulbrodner/alfresco-community-validator/releases/download/5.2.N-0.0.1/alfresco-community-validator-5.2.N-0.0.1-all-tests.jar

language: java

sudo: required

services:
  - docker

before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker-compose version
- export JOLOKIA_WAR=http://search.maven.org/remotecontent?filepath=org/jolokia/jolokia-war/1.3.7/jolokia-war-1.3.7.war
- export COMMUNITY_DISTRIBUTION=distribution/$(basename ${COMMUNITY_DISTRIBUTION_URL})
- wget ${ALFRESCO_COMMUNITY_VALIDATOR_TESTS} alfresco-community-validator-tests.jar
script: 
- export BACKGROUND=true && ./start.sh ${COMMUNITY_DISTRIBUTION_URL}
- ls -la ./helpers
- ls -la
after_script:
- docker-compose down